export const ItemData = [
    [
      {
        name: "Core i7 Desktop PC",
        price: 1800,
        category: "Desktop Computer",
        imgSrc: "Corei7DesktopPC.jpg",
        processor: "Intel Core i7-11700K",
        rams: [
          { name: "32GB DDR4", priceDifference: 0 },
          { name: "64GB DDR4", priceDifference: 300 },
          { name: "128GB DDR4", priceDifference: 600 },
        ],
        storages: [
          { name: "1TB NVMe SSD", priceDifference: 0 },
          { name: "2TB NVMe SSD", priceDifference: 200 },
          { name: "4TB NVMe SSD", priceDifference: 500 },
        ],
        gpu: "Nvidia RTX 3070",
        colors: ["Black", "Silver", "White"],
        discount: 0,
      },
    
      {
        name: "Gaming Nexus",
        price: 2300,
        category: "Desktop Computer",
        imgSrc: "GamingNexus.jpg",
        processor: "AMD Ryzen 9 5900X",
        rams: [
          { name: "64GB DDR4", priceDifference: 0 },
          { name: "128GB DDR4", priceDifference: 400 },
          { name: "256GB DDR4", priceDifference: 800 },
        ],
        storages: [
          { name: "2TB NVMe SSD", priceDifference: 0 },
          { name: "4TB NVMe SSD", priceDifference: 300 },
          { name: "8TB NVMe SSD", priceDifference: 800 },
        ],
        gpu: "Nvidia RTX 3080",
        colors: ["Black", "Red", "Blue"],
        discount: 200,
      },
    
      {
        name: "MiniFusion PC",
        price: 1200,
        category: "Desktop Computer",
        imgSrc: "MiniFusionPC.jpg",
        processor: "Intel Core i5-11600",
        rams: [
          { name: "16GB DDR4", priceDifference: 0 },
          { name: "32GB DDR4", priceDifference: 200 },
        ],
        storages: [
          { name: "512GB NVMe SSD", priceDifference: 0 },
          { name: "1TB NVMe SSD", priceDifference: 100 },
        ],
        gpu: "Nvidia GTX 1660 Super",
        colors: ["Black", "White"],
        discount: 0,
      },
    
      {
        name: "All-in-One Elite",
        price: 1700,
        category: "Desktop Computer",
        imgSrc: "AllInOneElite.jpg",
        processor: "Intel Core i9-11900",
        rams: [
          { name: "32GB DDR4", priceDifference: 0 },
          { name: "64GB DDR4", priceDifference: 400 },
        ],
        storages: [
          { name: "1TB NVMe SSD", priceDifference: 0 },
          { name: "2TB NVMe SSD", priceDifference: 200 },
        ],
        gpu: "Nvidia RTX 3060",
        colors: ["Silver", "Black"],
        discount: 0,
      },
    
      {
        name: "WorkForce Pro",
        price: 1400,
        category: "Desktop Computer",
        imgSrc: "WorkForcePro.jpg",
        processor: "AMD Ryzen 7 5800X",
        rams: [
          { name: "32GB DDR4", priceDifference: 0 },
          { name: "64GB DDR4", priceDifference: 300 },
        ],
        storages: [
          { name: "512GB NVMe SSD + 2TB HDD", priceDifference: 0 },
          { name: "1TB NVMe SSD + 4TB HDD", priceDifference: 200 },
        ],
        gpu: "AMD Radeon RX 6700 XT",
        colors: ["Black", "Red"],
        discount: 0,
      },
    
      {
        name: "Ryzen Beast",
        price: 2000,
        category: "Desktop Computer",
        imgSrc: "RyzenBeast.jpg",
        processor: "AMD Ryzen 9 5950X",
        rams: [
          { name: "64GB DDR4", priceDifference: 0 },
          { name: "128GB DDR4", priceDifference: 600 },
        ],
        storages: [
          { name: "2TB NVMe SSD", priceDifference: 0 },
          { name: "4TB NVMe SSD", priceDifference: 300 },
        ],
        gpu: "Nvidia RTX 3090",
        colors: ["Black", "Silver"],
        discount: 0,
      },
    ],
    [
      {
        name: "Ultrablade",
        price: 1600,
        category: "Laptop and Notebook",
        imgSrc: "Ultrablade.jpg",
        processor: "Intel Core i7-11800H",
        rams: [
          { name: "16GB DDR4", priceDifference: 0 },
          { name: "32GB DDR4", priceDifference: 200 },
        ],
        storages: [
          { name: "1TB NVMe SSD", priceDifference: 0 },
          { name: "2TB NVMe SSD", priceDifference: 150 },
        ],
        gpu: "Nvidia GTX 3060",
        colors: ["Gray", "Black"],
        discount: 300,
      },
    
      {
        name: "Gaming Fury",
        price: 2100,
        category: "Laptop and Notebook",
        imgSrc: "GamingFury.jpg",
        processor: "AMD Ryzen 7 5800H",
        rams: [
          { name: "32GB DDR4", priceDifference: 0 },
          { name: "64GB DDR4", priceDifference: 300 },
        ],
        storages: [
          { name: "2TB NVMe SSD", priceDifference: 0 },
          { name: "4TB NVMe SSD", priceDifference: 200 },
        ],
        gpu: "Nvidia RTX 3070",
        colors: ["Black", "Red"],
        discount: 0,
      },
    
        {
          name: "FlexiBook Pro",
          price: 1800,
          category: "Laptop and Notebook",
          imgSrc: "FlexiBookPro.jpg",
          processor: "Intel Core i9-11900H",
          rams: [
            { name: "32GB DDR4", priceDifference: 0 },
            { name: "64GB DDR4", priceDifference: 400 },
          ],
          storages: [
            { name: "1TB NVMe SSD", priceDifference: 0 },
            { name: "2TB NVMe SSD", priceDifference: 200 },
          ],
          gpu: "Nvidia RTX 3060",
          colors: ["Silver", "Black", "Blue"],
          discount: 150,
        },
        {
          name: "ZenBook Air",
          price: 1500,
          category: "Laptop and Notebook",
          imgSrc: "ZenBookAir.jpg",
          processor: "Intel Core i7-1165G7",
          rams: [
            { name: "16GB DDR4", priceDifference: 0 },
            { name: "32GB DDR4", priceDifference: 200 },
          ],
          storages: [
            { name: "512GB NVMe SSD", priceDifference: 0 },
            { name: "1TB NVMe SSD", priceDifference: 100 },
          ],
          gpu: "Intel Iris Xe Graphics",
          colors: ["Silver", "Blue", "Pink"],
          discount: 0,
        },
        {
          name: "SwiftBook Pro",
          price: 1700,
          category: "Laptop and Notebook",
          imgSrc: "SwiftBookPro.jpg",
          processor: "AMD Ryzen 9 5900HS",
          rams: [
            { name: "32GB DDR4", priceDifference: 0 },
            { name: "64GB DDR4", priceDifference: 300 },
          ],
          storages: [
            { name: "1TB NVMe SSD", priceDifference: 0 },
            { name: "2TB NVMe SSD", priceDifference: 150 },
          ],
          gpu: "Nvidia GTX 1650",
          colors: ["Silver", "Black", "Green"],
          discount: 0,
        },
        {
          name: "ProBook Phoenix",
          price: 2200,
          category: "Laptop and Notebook",
          imgSrc: "ProBookPhoenix.jpg",
          processor: "Intel Core i9-11900H",
          rams: [
            { name: "32GB DDR4", priceDifference: 0 },
            { name: "64GB DDR4", priceDifference: 400 },
          ],
          storages: [
            { name: "1TB NVMe SSD", priceDifference: 0 },
            { name: "2TB NVMe SSD", priceDifference: 200 },
          ],
          gpu: "Nvidia RTX 3070",
          colors: ["Black", "Red"],
          discount: 0,
        },
    ],
    [
        {
          name: "PlayStation 5",
          price: 500,
          category: "Console",
          imgSrc: "PlayStation5.jpg",
          processor: "Custom AMD Ryzen Zen 2",
          storage: "825GB SSD",
          gpu: "AMD Radeon RDNA 2",
          colors: ["White", "Black"],
          discount: 0,
        },
        {
          name: "Xbox Series X",
          price: 550,
          category: "Console",
          imgSrc: "XboxSeriesX.jpg",
          processor: "Custom AMD Ryzen Zen 2",
          storage: "1TB NVMe SSD",
          gpu: "AMD Radeon RDNA 2",
          colors: ["Black"],
          discount: 50,
        },
        {
          name: "Nintendo Switch",
          price: 300,
          category: "Console",
          imgSrc: "NintendoSwitch.jpg",
          processor: "Custom NVIDIA Tegra X1",
          storage: "32GB eMMC",
          gpu: "NVIDIA Maxwell",
          colors: ["Red/Blue", "Gray"],
          discount: 0,
        },
        {
          name: "PlayStation 5 Digital Edition",
          price: 400,
          category: "Console",
          imgSrc: "PlayStation5DigitalEdition.jpg",
          processor: "Custom AMD Ryzen Zen 2",
          storage: "825GB SSD",
          gpu: "AMD Radeon RDNA 2",
          colors: ["White", "Black"],
          discount: 0,
        },
        {
          name: "Xbox Series S",
          price: 300,
          category: "Console",
          imgSrc: "XboxSeriesS.jpg",
          processor: "Custom AMD Ryzen Zen 2",
          storage: "512GB NVMe SSD",
          gpu: "AMD Radeon RDNA 2",
          colors: ["White"],
          discount: 40,
        },
        {
          name: "Nintendo Switch OLED",
          price: 350,
          category: "Console",
          imgSrc: "NintendoSwitchOLED.jpg",
          processor: "Custom NVIDIA Tegra X1",
          storage: "64GB eMMC",
          gpu: "NVIDIA Maxwell",
          colors: ["White", "Black"],
          discount: 0,
        },
      ],
      [
        {
          name: "Dell UltraSharp U2419H",
          price: 250,
          category: "Monitor",
          imgSrc: "DellUltraSharpU2419H.jpg",
          displaySize: "24 inches",
          resolution: "1920 x 1080 (Full HD)",
          refreshRate: "60Hz",
          panelType: "IPS",
          colors: ["Black"],
          discount: 0,
        },
        {
          name: "ASUS ROG Swift PG279Q",
          price: 700,
          category: "Monitor",
          imgSrc: "ASUSROGSwiftPG279Q.jpg",
          displaySize: "27 inches",
          resolution: "2560 x 1440 (Quad HD)",
          refreshRate: "165Hz",
          panelType: "IPS",
          colors: ["Black"],
          discount: 130,
        },
        {
          name: "LG 27GL850-B",
          price: 450,
          category: "Monitor",
          imgSrc: "LG27GL850-B.jpg",
          displaySize: "27 inches",
          resolution: "2560 x 1440 (Quad HD)",
          refreshRate: "144Hz",
          panelType: "Nano IPS",
          colors: ["Black"],
          discount: 0,
        },
        {
          name: "Acer R240HY",
          price: 150,
          category: "Monitor",
          imgSrc: "AcerR240HY.jpg",
          displaySize: "23.8 inches",
          resolution: "1920 x 1080 (Full HD)",
          refreshRate: "60Hz",
          panelType: "IPS",
          colors: ["Black"],
          discount: 0,
        },
        {
          name: "Samsung Odyssey G7",
          price: 800,
          category: "Monitor",
          imgSrc: "SamsungOdysseyG7.jpg",
          displaySize: "27 inches",
          resolution: "2560 x 1440 (Quad HD)",
          refreshRate: "240Hz",
          panelType: "VA",
          colors: ["Black"],
          discount: 150,
        },
        {
          name: "ViewSonic XG2402",
          price: 250,
          category: "Monitor",
          imgSrc: "ViewSonicXG2402.jpg",
          displaySize: "24 inches",
          resolution: "1920 x 1080 (Full HD)",
          refreshRate: "144Hz",
          panelType: "TN",
          colors: ["Black"],
          discount: 0,
        },
      ],
      [
        {
          name: "HyperX Cloud II",
          price: 100,
          category: "Headset",
          imgSrc: "HyperXCloudII.jpg",
          connectionType: "Wired (USB)",
          compatibility: "PC, PS4, Xbox One",
          soundType: "7.1 Virtual Surround Sound",
          microphone: "Detachable Noise-Canceling",
          colors: ["Black", "Red"],
          discount: 0,
        },
        {
          name: "SteelSeries Arctis Pro Wireless",
          price: 330,
          category: "Headset",
          imgSrc: "SteelSeriesArctisProWireless.jpg",
          connectionType: "Wireless (Lossless 2.4 GHz)",
          compatibility: "PC, PS4, PS5",
          soundType: "DTS Headphone:X v2.0",
          microphone: "Retractable ClearCast",
          colors: ["Black"],
          discount: 40,
        },
        {
          name: "Razer BlackShark V2 Pro",
          price: 180,
          category: "Headset",
          imgSrc: "RazerBlackSharkV2Pro.jpg",
          connectionType: "Wireless (2.4 GHz USB Dongle)",
          compatibility: "PC, PS4",
          soundType: "THX Spatial Audio",
          microphone: "Detachable HyperClear",
          colors: ["Black"],
          discount: 0,
        },
        {
          name: "Corsair HS60 PRO",
          price: 60,
          category: "Headset",
          imgSrc: "CorsairHS60PRO.jpg",
          connectionType: "Wired (USB)",
          compatibility: "PC, PS4, Xbox One",
          soundType: "Virtual 7.1 Surround Sound",
          microphone: "Detachable Noise-Canceling",
          colors: ["Carbon", "Yellow", "White"],
          discount: 0,
        },
        {
          name: "Logitech G Pro X",
          price: 130,
          category: "Headset",
          imgSrc: "LogitechGProX.jpg",
          connectionType: "Wired (USB)",
          compatibility: "PC, PS4, Xbox One, Nintendo Switch",
          soundType: "DTS Headphone:X 2.0",
          microphone: "Blue VO!CE Technology",
          colors: ["Black"],
          discount: 0,
        },
        {
          name: "Sennheiser HD 660 S",
          price: 430,
          category: "Headset",
          imgSrc: "SennheiserHD660S.jpg",
          connectionType: "Wired (3.5mm)",
          compatibility: "PC, Mac, PS4, Xbox One, Mobile",
          soundType: "Open-Back Audiophile Headphones",
          microphone: "No microphone",
          colors: ["Black"],
          discount: 80,
        },
      ],
      // Add more categories...
    ];
    